// Code generated by alef — DO NOT EDIT.
// alef:hash:15e6f3cab21d550b0dbb6b6eb14df702cfca59e0545ab78850dbaeba1c0d11bb
package htmltomarkdown

// RequireNativeSetup_3_12_2 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_3_12_2 = "3.12.2"
