# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b437934172df08e99b144908abf28f8f9afe1baac2efe49a76284a468a4764b
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module HtmlToMarkdown
  ## The version string for this package.
  VERSION = "3.12.2"
end
