// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9860b2e5b62d8e7768b3bb7606381c00b81dc3d64b298779185cc68763354616
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
    name: "E2eSwift",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    dependencies: [
        .package(path: "../../packages/swift"),
    ],
    targets: [
        .testTarget(
            name: "HtmlToMarkdownE2ETests",
            dependencies: [.product(name: "HtmlToMarkdown", package: "swift")]
        ),
    ]
)
