// swift-tools-version: 6.0
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e3fb8392a529e67caed938a981cb7a048ff47424d5c791af561b88aae9cece42
// To regenerate: alef generate
// To verify freshness: alef verify

import PackageDescription

let package = Package(
  name: "E2eSwift",
  platforms: [
    .macOS(.v13),
    .iOS(.v16),
  ],
  dependencies: [
    .package(url: "https://github.com/xberg-io/html-to-markdown", branch: "release/swift/3.12.2"),
  ],
  targets: [
    .testTarget(
      name: "HtmlToMarkdownE2ETests",
      dependencies: [.product(name: "HtmlToMarkdown", package: "html-to-markdown")]
    ),
  ]
)
